{
 "title": "FIAP Hackathon API Monitoring",
 "tags": [
  "fiap",
  "hackathon",
  "api"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{endpoint!=\"/metrics\", endpoint!=\"/health\"})"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{endpoint!=\"/metrics\", endpoint!=\"/health\"}[1m]))"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint!=\"/metrics\", endpoint!=\"/health\"}[1m])) / sum(rate(http_request_duration_seconds_count{endpoint!=\"/metrics\", endpoint!=\"/health\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests in Progress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_in_progress)" }
   ]
  }
 ]
}