apiVersion: v1
kind: Secret
metadata:
  name: fiap-hackathon-secret
  namespace: fiap-hackathon
type: Opaque
stringData:
  SqlServer__SaPassword: "CHANGE_ME"

  ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=FIAPHackathon;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True"

  Jwt__Key: "CHANGE_ME"

  RabbitMq__Password: "CHANGE_ME"

  Grafana__AdminUser: "admin"
  Grafana__AdminPassword: "CHANGE_ME"

  Zabbix__PostgresPassword: "CHANGE_ME"