apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-postgres-data
  namespace: fiap-hackathon

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-postgres
  namespace: fiap-hackathon

spec:
  replicas: 1

  selector:
    matchLabels:
      app: zabbix-postgres

  template:
    metadata:
      labels:
        app: zabbix-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: "zabbix"

            - name: POSTGRES_USER
              value: "zabbix"

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiap-hackathon-secret
                  key: Zabbix__PostgresPassword

          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10

          volumeMounts:
            - name: zabbix-postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: zabbix-postgres-data
          persistentVolumeClaim:
            claimName: zabbix-postgres-data

---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgres
  namespace: fiap-hackathon

spec:
  selector:
    app: zabbix-postgres

  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

  type: ClusterIP