# Nome do workflow
name: CD

# Execução
on:
  # Automatica via push
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

  # manual pelo GitHub
  workflow_dispatch:

# Permissões necessárias para autenticação OIDC
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    # Runner Linux
    runs-on: ubuntu-latest

    # Environment configurado no GitHub
    environment: dev

    steps:
      # Baixa o código do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Login no Azure usando OIDC
      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Autentica o runner no Azure Container Registry
      - name: Login no ACR
        run: az acr login --name acrFiapHackathon

      # Gera a imagem Docker da API
      - name: Build da imagem Docker
        run: |
          docker build \
            -f Hackathon.Api/Dockerfile \
            -t acrfiaphackathon.azurecr.io/fiap-hackathon-api:${{ github.sha }} \
            .

      # Publica a imagem no ACR
      - name: Push da imagem para o ACR
        run: |
          docker push \
            acrfiaphackathon.azurecr.io/fiap-hackathon-api:${{ github.sha }}