name: CD

on:
  # Executa apos a conclusao do CI
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - dev

  # Permite execu��o manual
  workflow_dispatch:

# Permiss�es necess�rias para autentica��o OIDC
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    # Executa manualmente OU ap�s CI conclu�do com sucesso
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    # Environment do GitHub
    environment: dev

    # SHA que ser� utilizado nas imagens
    env:
      DEPLOY_SHA: ${{ github.event.workflow_run.head_sha || github.sha }}

    steps:
      # Baixa exatamente o c�digo que ser� implantado
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DEPLOY_SHA }}

      # Autentica no Azure utilizando OIDC
      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Autentica no Azure Container Registry
      - name: Login no ACR
        run: az acr login --name acrFiapHackathon

      # Gera a imagem Docker da API
      - name: Build da imagem Docker da API
        run: |
          docker build \
            -f Hackathon.Api/Dockerfile \
            -t acrfiaphackathon.azurecr.io/fiap-hackathon-api:${{ env.DEPLOY_SHA }} \
            .

      # Publica a imagem da API
      - name: Push da imagem da API
        run: |
          docker push \
            acrfiaphackathon.azurecr.io/fiap-hackathon-api:${{ env.DEPLOY_SHA }}

      # Gera a imagem Docker do Donation Worker
      - name: Build da imagem Docker do Donation Worker
        run: |
          docker build \
            -f Hackathon.DonationWorker/Dockerfile \
            -t acrfiaphackathon.azurecr.io/fiap-hackathon-donation-worker:${{ env.DEPLOY_SHA }} \
            .

      # Publica a imagem do Donation Worker
      - name: Push da imagem do Donation Worker
        run: |
          docker push \
            acrfiaphackathon.azurecr.io/fiap-hackathon-donation-worker:${{ env.DEPLOY_SHA }}

      # Atualiza a API no Azure Container Apps
      - name: Atualizar Container App da API
        run: |
          az containerapp update \
            --name fiap-hackathon-api-dev \
            --resource-group FIAPHackathon \
            --image acrfiaphackathon.azurecr.io/fiap-hackathon-api:${{ env.DEPLOY_SHA }}