name: CI

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:
  build:
    name: Build, Testes e Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Instalar .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependencias
        run: dotnet restore FIAPHackathon.slnx

      - name: Compilar solucao
        run: dotnet build FIAPHackathon.slnx --configuration Release --no-restore

      - name: Executar testes
        run: dotnet test FIAPHackathon.slnx --configuration Release --no-build

      - name: Gerar imagem Docker da API
        run: docker build -f Hackathon.Api/Dockerfile -t fiap-hackathon-api:${{ github.sha }} .
      - name: Gerar imagem Docker do Donation Worker
        run: docker build -f Hackathon.DonationWorker/Dockerfile -t fiap-hackathon-donation-worker:${{ github.sha }} .